AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Blooming Plant API - example AWS SAM template. Build TypeScript to `dist/` before packaging.

Resources:
  GetPlantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/getPlant.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Events:
        GetPlantById:
          Type: Api
          Properties:
            Path: /plants/{id}
            Method: GET
        SearchPlants:
          Type: Api
          Properties:
            Path: /plants
            Method: GET

  CreatePlantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/createPlant.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Events:
        CreatePlantApi:
          Type: Api
          Properties:
            Path: /plants
            Method: POST

  UpdatePlantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/updatePlant.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Events:
        UpdatePlantApi:
          Type: Api
          Properties:
            Path: /plants/{id}
            Method: PUT

  DeletePlantFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/handlers/deletePlant.handler
      Runtime: nodejs18.x
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Events:
        DeletePlantApi:
          Type: Api
          Properties:
            Path: /plants/{id}
            Method: DELETE
