#!/usr/bin/env bash
set -euo pipefail

# Create an API Key and Usage Plan for the PlantDatabaseApi
# Usage: ./scripts/create-api-key.sh [--key VALUE] [--api-name NAME] [--stage STAGE] [--usage-plan NAME] [--region REGION]

API_NAME="PlantDatabaseApi"
STAGE="prod"
USAGE_PLAN_NAME="PlantDatabaseUsagePlan"
KEY_NAME="PlantDatabaseApiKey"
# REGION will be resolved after parsing args: prefer explicit --region, else read AWS env vars or aws config
REGION=""
KEY_VALUE=""
FORCE_CREATE=0

usage(){
  cat <<EOF
Usage: $0 [options]
Options:
  --key VALUE        Provide an explicit API key value to use (optional)
  --api-name NAME    API Gateway RestApi name (default: ${API_NAME})
  --stage STAGE      API Gateway stage name (default: ${STAGE})
  --usage-plan NAME  Usage plan name (default: ${USAGE_PLAN_NAME})
  --region REGION    AWS region (default: ${REGION})
  --force            Force creation even if key with same name exists
  -h|--help          Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --key) KEY_VALUE="$2"; shift 2;;
    --api-name) API_NAME="$2"; shift 2;;
    --stage) STAGE="$2"; shift 2;;
    --usage-plan) USAGE_PLAN_NAME="$2"; shift 2;;
    --region) REGION="$2"; shift 2;;
    --force) FORCE_CREATE=1; shift 1;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown arg: $1"; usage; exit 1;;
  esac
done

# Resolve region: prefer explicit --region; else use env vars or aws config
if [[ -z "$REGION" ]]; then
  if [[ -n "${AWS_REGION:-}" ]]; then
    REGION="$AWS_REGION"
  elif [[ -n "${AWS_DEFAULT_REGION:-}" ]]; then
    REGION="$AWS_DEFAULT_REGION"
  else
    REGION=$(aws configure get region 2>/dev/null || true)
  fi
fi

if [[ -z "$REGION" || "$REGION" == "None" ]]; then
  echo "ERROR: No AWS region specified. Pass --region or configure a default region (via AWS_REGION, AWS_DEFAULT_REGION, or 'aws configure set region <region>')." >&2
  exit 2
fi

echo "Region: $REGION"
echo "Looking for RestApi named: $API_NAME"

REST_API_ID=$(aws apigateway get-rest-apis --region "$REGION" --query "items[?name=='${API_NAME}'].id | [0]" --output text)

if [[ -z "$REST_API_ID" || "$REST_API_ID" == "None" ]]; then
  echo "ERROR: RestApi named '$API_NAME' not found in region $REGION. Ensure your stack deployed successfully." >&2
  exit 2
fi

echo "Found RestApi id: $REST_API_ID"

# Check for existing API key with the same name
EXISTING_KEY_ID=$(aws apigateway get-api-keys --name-query "$KEY_NAME" --include-values --region "$REGION" --query "items[?name=='${KEY_NAME}'].[id] | [0]" --output text || true)
if [[ -n "$EXISTING_KEY_ID" && "$EXISTING_KEY_ID" != "None" && $FORCE_CREATE -eq 0 ]]; then
  echo "An API key named '$KEY_NAME' already exists (id: $EXISTING_KEY_ID)." 
  echo "Retrieve its value with: aws apigateway get-api-keys --name-query $KEY_NAME --include-values --region $REGION"
  exit 0
fi

if [[ -n "$KEY_VALUE" ]]; then
  echo "Creating API key with provided value..."
  KEY_OUTPUT=$(aws apigateway create-api-key --name "$KEY_NAME" --enabled --value "$KEY_VALUE" --region "$REGION" --query "join('|',[id,value])" --output text)
else
  echo "Creating API key (value will be generated by AWS)..."
  KEY_OUTPUT=$(aws apigateway create-api-key --name "$KEY_NAME" --enabled --region "$REGION" --query "join('|',[id,value])" --output text)
fi

KEY_ID=${KEY_OUTPUT%%|*}
KEY_VAL=${KEY_OUTPUT##*|}

echo "Created API Key id: $KEY_ID"
echo "API Key value: $KEY_VAL"

# Create or reuse usage plan
EXISTING_PLAN_ID=$(aws apigateway get-usage-plans --region "$REGION" --query "items[?name=='${USAGE_PLAN_NAME}'].id | [0]" --output text || true)
if [[ -n "$EXISTING_PLAN_ID" && "$EXISTING_PLAN_ID" != "None" ]]; then
  echo "Reusing existing UsagePlan id: $EXISTING_PLAN_ID"
  USAGE_PLAN_ID=$EXISTING_PLAN_ID
else
  echo "Creating UsagePlan '${USAGE_PLAN_NAME}' and attaching API stage ${REST_API_ID}:${STAGE}"
  USAGE_PLAN_ID=$(aws apigateway create-usage-plan --name "$USAGE_PLAN_NAME" --api-stages apiId=$REST_API_ID,stage=$STAGE --region "$REGION" --query 'id' --output text)
  echo "Created UsagePlan id: $USAGE_PLAN_ID"
fi

# Associate API key with usage plan
echo "Associating API Key with Usage Plan..."
aws apigateway create-usage-plan-key --usage-plan-id "$USAGE_PLAN_ID" --key-id "$KEY_ID" --key-type API_KEY --region "$REGION"

echo
echo "DONE"
echo "API Gateway REST API id: $REST_API_ID"
echo "Stage: $STAGE"
echo "UsagePlan id: $USAGE_PLAN_ID"
echo "API Key id: $KEY_ID"
echo "API Key value: $KEY_VAL"
echo
echo "Test the API with the header: -H 'x-api-key: $KEY_VAL'"
