const fs = require('fs');
const path = require('path');

const SOURCE_FILE = path.join(__dirname, './data/aliases.json');
const OUTPUT_DIR = path.join(__dirname, '../src/data/aliasShards');
const MAP_FILE = path.join(__dirname, '../src/data/aliasShardMap.ts');
const LETTERS = 'abcdefghijklmnopqrstuvwxyz';
const FALLBACK_BUCKET = 'misc';

function readAliases() {
  if (!fs.existsSync(SOURCE_FILE)) {
    throw new Error(`Source aliases file not found: ${SOURCE_FILE}`);
  }
  const raw = fs.readFileSync(SOURCE_FILE, 'utf-8');
  return JSON.parse(raw);
}

function bucketForAlias(alias) {
  if (!alias || typeof alias !== 'string') {
    return FALLBACK_BUCKET;
  }
  const first = alias.trim().charAt(0).toLowerCase();
  if (first && LETTERS.includes(first)) {
    return first;
  }
  return FALLBACK_BUCKET;
}

function partitionAliases(aliasMap) {
  const buckets = {};
  for (const [alias, pks] of Object.entries(aliasMap)) {
    const bucket = bucketForAlias(alias);
    if (!buckets[bucket]) {
      buckets[bucket] = {};
    }
    buckets[bucket][alias] = pks;
  }
  return buckets;
}

function resetOutputDir() {
  fs.rmSync(OUTPUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

function writeBucketFiles(buckets) {
  const keys = Object.keys(buckets).sort();
  for (const key of keys) {
    const filePath = path.join(OUTPUT_DIR, `${key}.json`);
    fs.writeFileSync(filePath, JSON.stringify(buckets[key], null, 2));
    console.log(`Wrote ${Object.keys(buckets[key]).length} aliases to ${filePath}`);
  }
  return keys;
}

function buildImportName(key) {
  if (/^[a-z]$/.test(key)) {
    return `${key}Shard`;
  }
  return `${key.replace(/[^a-z0-9]/gi, '_')}Shard`;
}

function writeTypeScriptMap(keys) {
  const importLines = keys
    .map((key) => `import ${buildImportName(key)} from './aliasShards/${key}.json';`)
    .join('\n');

  const mapEntries = keys
    .map((key) => `  '${key}': ${buildImportName(key)},`)
    .join('\n');

  const content = `// Auto-generated by scripts/split_aliases_by_letter.js\n${importLines}\n\nexport const aliasShardMap: Record<string, Record<string, string[]>> = {\n${mapEntries}\n};\n\nexport const DEFAULT_ALIAS_SHARD_KEY = '${FALLBACK_BUCKET}';\n`;
  fs.writeFileSync(MAP_FILE, content);
  console.log(`Alias shard map written to ${MAP_FILE}`);
}

function main() {
  try {
    const aliases = readAliases();
    const buckets = partitionAliases(aliases);
    resetOutputDir();
    const keys = writeBucketFiles(buckets);
    writeTypeScriptMap(keys);
    console.log('Alias splitting complete.');
  } catch (err) {
    console.error(err.message);
    process.exit(1);
  }
}

main();
